In [11]:
import yfinance as yf

In [23]:
ticker = "SOFI"
data = yf.download(ticker, period="1y")

[*********************100%%**********************]  1 of 1 completed

In [15]:
sofi = yf.Ticker("SOFI")

# get historical market data
hist = sofi.history(period="1mo")

In [16]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-13 00:00:00-04:00,7.100,7.130,6.770,6.80,51888300,0.0,0.0
2024-06-14 00:00:00-04:00,6.710,6.765,6.430,6.46,75531400,0.0,0.0
2024-06-17 00:00:00-04:00,6.460,6.490,6.300,6.46,45193300,0.0,0.0
2024-06-18 00:00:00-04:00,6.460,6.600,6.390,6.42,28420200,0.0,0.0
2024-06-20 00:00:00-04:00,6.420,6.450,6.260,6.32,31396900,0.0,0.0
2024-06-21 00:00:00-04:00,6.300,6.350,6.200,6.32,34537200,0.0,0.0
2024-06-24 00:00:00-04:00,6.320,6.570,6.300,6.54,32286900,0.0,0.0
2024-06-25 00:00:00-04:00,6.540,6.540,6.410,6.45,19627200,0.0,0.0
2024-06-26 00:00:00-04:00,6.400,6.480,6.360,6.46,18400200,0.0,0.0
2024-06-27 00:00:00-04:00,6.410,6.540,6.360,6.54,18808000,0.0,0.0
2024-06-28 00:00:00-04:00,6.600,6.650,6.530,6.61,30002000,0.0,0.0
2024-07-01 00:00:00-04:00,6.600,6.670,6.415,6.43,30828100,0.0,0.0
2024-07-02 00:00:00-04:00,6.430,6.480,6.290,6.45,26977400,0.0,0.0
2024-07-03 00:00:00-04:00,6.480,6.550,6.415,6.52,15364300,0.0,0.0
2024-07-05 00:00:00-04:00,6.480,6.510,6.380,6.47,15639700,0.0,0.0
2024-07-08 00:00:00-04:00,6.485,6.530,6.350,6.35,22763700,0.0,0.0
2024-07-09 00:00:00-04:00,6.350,6.380,6.150,6.38,40392200,0.0,0.0
2024-07-10 00:00:00-04:00,6.420,6.620,6.320,6.57,37482300,0.0,0.0
2024-07-11 00:00:00-04:00,6.800,6.930,6.680,6.77,46656300,0.0,0.0
2024-07-12 00:00:00-04:00,6.890,7.000,6.810,6.97,36944900,0.0,0.0

In [24]:
data.to_csv(f'../dataset/{ticker}.csv', header=True)